name: Android CI

on:
  push:
    branches:
      - main  # or the branch you want to trigger the build from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Install Android SDK
      run: |
        sudo apt-get update -y
        sudo apt-get install -y openjdk-11-jdk wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip commandlinetools-linux-8512546_latest.zip -d $HOME/cmdline-tools
        mkdir -p $ANDROID_HOME/cmdline-tools
        mv $HOME/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-30" "build-tools;30.0.2"

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v2
      with:
        name: hello-world-apk
        path: app/build/outputs/apk/debug/app-debug.apk



on:
  push:
    branches:
      - master
  workflow_dispatch:
